# Generated by Django 4.2.7 on 2023-11-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_task_due_date_alter_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
